In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("Nigeria_1997-2024_Sep20.csv")

In [4]:
df.head()

,event_id_cnty,event_date,year,time_precision,disorder_type,event_type,sub_event_type,actor1,assoc_actor_1,inter1,...,location,latitude,longitude,geo_precision,source,source_scale,notes,fatalities,tags,timestamp
0,NIG38575,2024-09-20,2024,1,Demonstrations,Protests,Peaceful protest,Protesters (Nigeria),Refugees/IDPs (Nigeria),6,...,Bolori,11.8826,13.0890,1,Whatsapp,New media,"On 20 September 2024, IDPs (flood victims) fro...",0,crowd size=no report,1727134598
1,NIG38585,2024-09-20,2024,2,Demonstrations,Protests,Peaceful protest,Protesters (Nigeria),Muslim Group (Nigeria),6,...,Ile-Ife,7.4824,4.5603,1,Daily Trust (Nigeria),National,"Around 20 September 2024 (as reported), hundre...",0,crowd size=hundreds,1727134598
2,NIG38581,2024-09-19,2024,1,Demonstrations,Protests,Peaceful protest,Protesters (Nigeria),NaN,6,...,Agodi,7.4035,3.9132,1,Daily Post (Nigeria); Guardian (Nigeria); Saha...,National-Regional,"On 19 September 2024, for a second consecutive...",0,crowd size=hundreds,1727134598
3,NIG38588,2024-09-19,2024,1,Strategic developments,Strategic developments,Disrupted weapons use,Police Forces of Nigeria (2023-),NaN,1,...,Buruku,10.6179,7.2331,1,Daily Post (Nigeria); Nigeria Punch,National,"Weapons seizure: On 19 September 2024, Police ...",0,NaN,1727134598
4,NIG38591,2024-09-19,2024,1,Demonstrations,Protests,Peaceful protest,Protesters (Nigeria),PDP: People's Democratic Party,6,...,Wanno,7.1389,6.5724,1,Vanguard (Nigeria),National,"On 19 September 2024, PDP youths protested at ...",0,crowd size=no report,1727134598

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38076 entries, 0 to 38075
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   event_id_cnty       38076 non-null  object
 1   event_date          38076 non-null  object
 2   year                38076 non-null  int64
 3   time_precision      38076 non-null  int64
 4   disorder_type       38076 non-null  object
 5   event_type          38076 non-null  object
 6   sub_event_type      38076 non-null  object
 7   actor1              38076 non-null  object
 8   assoc_actor_1       10199 non-null  object
 9   inter1              38076 non-null  int64
 10  actor2              29525 non-null  object
 11  assoc_actor_2       8803 non-null   object
 12  inter2              38076 non-null  int64
 13  interaction         38076 non-null  int64
 14  civilian_targeting  14964 non-null  object
 15  iso                 38076 non-null  int64
 16  region              38076 non-null  object
 17  country             38076 non-null  object
 18  admin1              38075 non-null  object
 19  admin2              38075 non-null  object
 20  admin3              0 non-null      float64
 21  location            38076 non-null  object
 22  latitude            38076 non-null  float64
 23  longitude           38076 non-null  float64
 24  geo_precision       38076 non-null  int64
 25  source              38076 non-null  object
 26  source_scale        38076 non-null  object
 27  notes               38076 non-null  object
 28  fatalities          38076 non-null  int64
 29  tags                7514 non-null   object
 30  timestamp           38076 non-null  int64
dtypes: float64(3), int64(9), object(19)
memory usage: 9.0+ MB

In [6]:
df.columns

Index(['event_id_cnty', 'event_date', 'year', 'time_precision',
       'disorder_type', 'event_type', 'sub_event_type', 'actor1',
       'assoc_actor_1', 'inter1', 'actor2', 'assoc_actor_2', 'inter2',
       'interaction', 'civilian_targeting', 'iso', 'region', 'country',
       'admin1', 'admin2', 'admin3', 'location', 'latitude', 'longitude',
       'geo_precision', 'source', 'source_scale', 'notes', 'fatalities',
       'tags', 'timestamp'],
      dtype='object')

# Data Cleaning

In [7]:
# Changing the event date data type to datetime
df["event_date"] = pd.to_datetime(df["event_date"], format="%Y-%m-%d")

In [8]:
df["year"] = df["event_date"].dt.year

In [9]:
df.head()

,event_id_cnty,event_date,year,time_precision,disorder_type,event_type,sub_event_type,actor1,assoc_actor_1,inter1,...,location,latitude,longitude,geo_precision,source,source_scale,notes,fatalities,tags,timestamp
0,NIG38575,2024-09-20,2024,1,Demonstrations,Protests,Peaceful protest,Protesters (Nigeria),Refugees/IDPs (Nigeria),6,...,Bolori,11.8826,13.0890,1,Whatsapp,New media,"On 20 September 2024, IDPs (flood victims) fro...",0,crowd size=no report,1727134598
1,NIG38585,2024-09-20,2024,2,Demonstrations,Protests,Peaceful protest,Protesters (Nigeria),Muslim Group (Nigeria),6,...,Ile-Ife,7.4824,4.5603,1,Daily Trust (Nigeria),National,"Around 20 September 2024 (as reported), hundre...",0,crowd size=hundreds,1727134598
2,NIG38581,2024-09-19,2024,1,Demonstrations,Protests,Peaceful protest,Protesters (Nigeria),NaN,6,...,Agodi,7.4035,3.9132,1,Daily Post (Nigeria); Guardian (Nigeria); Saha...,National-Regional,"On 19 September 2024, for a second consecutive...",0,crowd size=hundreds,1727134598
3,NIG38588,2024-09-19,2024,1,Strategic developments,Strategic developments,Disrupted weapons use,Police Forces of Nigeria (2023-),NaN,1,...,Buruku,10.6179,7.2331,1,Daily Post (Nigeria); Nigeria Punch,National,"Weapons seizure: On 19 September 2024, Police ...",0,NaN,1727134598
4,NIG38591,2024-09-19,2024,1,Demonstrations,Protests,Peaceful protest,Protesters (Nigeria),PDP: People's Democratic Party,6,...,Wanno,7.1389,6.5724,1,Vanguard (Nigeria),National,"On 19 September 2024, PDP youths protested at ...",0,crowd size=no report,1727134598

In [10]:
# Summing null values in columns
null_columns=df.columns[df.isnull().any()]
for i in null_columns:
    print(i,df[i].isnull().sum())

assoc_actor_1 27877
actor2 8551
assoc_actor_2 29273
civilian_targeting 23112
admin1 1
admin2 1
admin3 38076
tags 30562

In [11]:
# Dropping colums with null values and irrelevant
df_cleaned = df.drop(columns=['admin3', 'timestamp','tags','event_id_cnty','time_precision',
                              'geo_precision','notes','source','source_scale','country','region','assoc_actor_1',
                              'assoc_actor_2','inter2','actor2','interaction','iso', "civilian_targeting"])

In [12]:
# Checking for column unique values
for col in df_cleaned.columns:
    print(col, df_cleaned[col].nunique())

event_date 6513
year 28
disorder_type 4
event_type 6
sub_event_type 24
actor1 881
inter1 8
admin1 37
admin2 751
location 5116
latitude 4935
longitude 5013
fatalities 134

In [13]:
df_cleaned[["admin1", "admin2"]]

            admin1           admin2
0            Borno  Maiduguri Metro
1             Osun      Ife Central
2              Oyo     Ibadan North
3           Kaduna           Chikun
4              Edo      Etsako East
...            ...              ...
38071        Delta      Warri South
38072      Bayelsa          Sagbama
38073         Kogi           Lokoja
38074  Cross River           Yakurr
38075        Lagos     Lagos Island

[38076 rows x 2 columns]

In [14]:
# Drop admin1 and admin2 with missing values
df_cleaned.dropna(subset=['admin1', 'admin2'], inplace=True)

# Check for duplicates and remove if found
df_cleaned.drop_duplicates(inplace=True)

In [15]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37763 entries, 0 to 38075
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   event_date      37763 non-null  datetime64[ns]
 1   year            37763 non-null  int64
 2   disorder_type   37763 non-null  object
 3   event_type      37763 non-null  object
 4   sub_event_type  37763 non-null  object
 5   actor1          37763 non-null  object
 6   inter1          37763 non-null  int64
 7   admin1          37763 non-null  object
 8   admin2          37763 non-null  object
 9   location        37763 non-null  object
 10  latitude        37763 non-null  float64
 11  longitude       37763 non-null  float64
 12  fatalities      37763 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(3), object(7)
memory usage: 4.0+ MB

In [16]:
df_cleaned.head()

,event_date,year,disorder_type,event_type,sub_event_type,actor1,inter1,admin1,admin2,location,latitude,longitude,fatalities
0,2024-09-20,2024,Demonstrations,Protests,Peaceful protest,Protesters (Nigeria),6,Borno,Maiduguri Metro,Bolori,11.8826,13.0890,0
1,2024-09-20,2024,Demonstrations,Protests,Peaceful protest,Protesters (Nigeria),6,Osun,Ife Central,Ile-Ife,7.4824,4.5603,0
2,2024-09-19,2024,Demonstrations,Protests,Peaceful protest,Protesters (Nigeria),6,Oyo,Ibadan North,Agodi,7.4035,3.9132,0
3,2024-09-19,2024,Strategic developments,Strategic developments,Disrupted weapons use,Police Forces of Nigeria (2023-),1,Kaduna,Chikun,Buruku,10.6179,7.2331,0
4,2024-09-19,2024,Demonstrations,Protests,Peaceful protest,Protesters (Nigeria),6,Edo,Etsako East,Wanno,7.1389,6.5724,0

In [17]:
# save cleaned_dataframe to a new csv file
df_cleaned.to_csv('Nigeria_1997-2024_Sep20_cleaned.csv', index=False)